### ISSUE TITLE
The Voyage Process - Getting off to a Solid Start!

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v43-tier2-team-22#13]
**__Feature Description__**
Chingu has created a process for you to follow during the Voyage. This process helps you to get off on a solid start.

**__Major User Stories/tasks__**
- [x] Step 1: 🤝 Meet your team & schedule Kickoff meeting #5 
- [x] Step 2: 🧑‍🤝‍🧑 Conduct Kickoff meeting #6 
- [x] Step 3: 👍 Choose a project & create a Vision Statement #7 
- [x] Step 4: 📤 Define & prioritize MVP features #8 
- [ ] Step 5: 📋 Create a Project Backlog #9 
- [x] Step 6: 📝 Create a Low-fidelity wireframe #14 
- [x] Step 7: ⚙️ Set Up a Team Workflow #10 

**__Additional Considerations__**
N/a

**Comment by shijiezhou1** [comment]
Workflow: https://github.com/chingu-voyages/v43-tier2-team-22/issues/19
